[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "alfa"
version = "0.0.1"
description = "A minimalist platform for running trading strategies."
authors = ["Mircea Avram <mavram@gmail.com>"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
keywords = []
repository = "https://github.com/mavram/alfa"

[tool.poetry.dependencies]
python = ">=3.12"
dynaconf = "*"
yfinance = "*"

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
isort = "*"
pytest = "*"
pytest-cov = "*"

[tool.black]
line-length = 107
target-version = ["py39"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 107
multi_line_output = 3
include_trailing_comma = true
skip = ["bin", "dist", "include", "lib"]

[tool.pytest.ini_options]
addopts = "--verbose --disable-warnings"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
