[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alfa"
version = "0.0.1"
description = "A minimalist platform for running trading strategies."
authors = [
    { name = "Mircea Avram", email = "mavram@gmail.com" }
]
readme = "README.md"  # Specify if you have a README file
license = { text = "MIT License" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = ">=3.12"

dependencies = [
    "dynaconf",
    "setuptools",
    "yfinance"
]

[project.optional-dependencies]
development = [
    "black",
    "flake8",
    "pytest",
    "pytest-cov"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages]
find = { include = ["*"] }

[tool.black]
line-length = 89
target-version = ["py39"]
skip-string-normalization = false
