[global]
portfolio_name = "alpha"

[dev]
log_level = "DEBUG"
db_path = "data/dev-alpha.db"

[testing]
log_level = "WARNING"
db_path = "data/test-alpha.db"

[prod]
log_level = "INFO"
db_path = "data/alpha.db"
